version: '3'
services: 
    ms-sql-server:
        image: mcr.microsoft.com/mssql/server
        environment: 
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "reallyStrongPwd123"
            MSSQL_PID: Express
            ports: 
                 '1433:1433'
    music:
        build: .
        environment: 
            DBServer: "ms-sql-server"
        ports: 
            - "8080:80"